---
date: "May 13, 2016"
output:
  html_document:
    toc: yes
    toc_float: yes
---

Нежельский Александр
============

-----------------------------------------------
Россия, Москва      
nejel@mail.ru
+79296391943
https://github.com/nejel
-----------------------------------------------


Опыт работы
----------

**Текущее место работы:**

АО "Лаборатория Касперского".

Пришёл в компанию в августе 2015 года как стажер на должность Social Media Manager на первом курсе магистратуры НИУ ВШЭ. В течение года получил повышение в должность Event Specialist, а позже в Employer Branding Specialist. В настояший момент работаю в должности Project Manager.

Project manager. Основные обязанности:

- Работа в составе команды по развитию бренда работодателя "Лаборатории Касперского".
- Руководство внешними и внутренними командами разработки, взаимодействие с различными ресурсными подразделениями.
- Работа над проектами в сфере продвижения бренда работодателя в digital. 
- Работа с внутренними и внешними разработчиками над созданием сайтов и мобильных приложений. 
- Разработка бизнес-требований совместно с заказчиком, финализация технических требований и оформление ТЗ на разработку.
- Разработка бизнес-стратегии и стратегии цифрового продвижения продуктов. 
- Ведение глобальных образовательных инициатив "Лаборатории Касперского". 
- Формирование и согласование бюджетов проекта, создание плана и контроль сроков, выполнение и контроль выполнения задач на каждом этапе -- от формирования идеи до запуска в сеть, внедрение кей-фич продукта.
- Администрирование документации и задач в JIRA/Confluence.
- Работа в различных системах управления проектами, такими как Trello, RedMine, Asana, JIRA.
- Ведение проектов по Agile-методологии.

Ссылки на проекты, над которыми работал:

* https://events.kaspersky.com
* https://academy.kaspersky.com/
* https://career.kaspersky.com

**Pet project**

BTnews.me.

Технический директор в команде проекта BTnews.me. Основные обязанности:

- Разработка с нуля и запуск сайта на основе CMS (https://btnews.me).
- Интеграция, запуск и поддержка внутренних сервисов (базы знаний на wiki, Яндекс.Коннект и другие).
- Разработка, тестирование и внедрение кей-фич сайта.
- Управление доменами.
- Руководство командой из нескольких web-разработчиков.
- Создание и развитие новостного телеграм-бота @btnewsbot (парсинг новостей с сайта, распределение новостей в платформы).
- Digital-продвижение и развитие новостного телеграм-канала @btnewsme (с 0 до 2000+ читателей).

**Предыдущие места работы**

Триколор ТВ (ОАО НСК, www.tricolor.tv)
Специалист по настройке и ремонту клиентского оборудования. Основные обязанности:

- Приемка, настройка, обслуживание, ремонт клиентского и дилерского оборудование спутникового телесмотрения клиентов ОАО "НСК" (Триколор-ТВ).
- Ведение учета дилеров и клиентов в CRM.
- Коммуникация с внутренними заказчиками и внешними клиентами, оформление договоров, разрешение инцидентов.


Технические навыки
--------------------

    * Adobe Photoshop
    * Анализ данных
    * R studio
    * LSTM
    * Компьютерная лингвистика
    * Agile Project Management
    * Scrum 
    * Kanban
    * SQL
    * Linux
    * Business Analysis
    * R
    * GIT
    * GitHub
    * Domain administration
    * Atlassian JIRA
    * CMS Wordpress
    * CMF Modx (revo)
    * HTML5
    * CSS

Основатель и один из разработчиков проекта по компьтерной лингвистики #Нейробугурт. 
В ходе проекта LSTM-сеть на базе torch-rnn обучена на корпусе из 35 000 образцов для генерации текстов для социальных сетей медиапроекта.

Код проекта: https://github.com/Nejel/neural

Бизнес-результаты доступны [в социальных сетях.](https://vk.com/topic-57536014_34843046)


Образование
---------

2014-2016
:   **Магистр, Международные отношения: Азиатские исследования**; НИУ ВШЭ (Москва)

    *Диссертация: Информационная безопасность Японии*
    
2010-2014
:   **Бакалавр, Социология**; Волгоградский Государственный Университет (ВолГУ)

    *Диплом: Девиантное поведение молодежи в современном российском обществе*


Дополнительно
----------------------------------------

* Языки общения:

     * Русский (нативный)
     * Английский (Upper Intermediate)

* Основатель нескольких крупных пабликов Вконтакте (с совокупной аудиторией более 200к человек)

* Айкидока